apiVersion: v1
kind: Pod
metadata:
  labels:
    name: redis
    redis-sentinel: "true"
    role: master
  name: redis-master
spec:
  containers:
    - name: master
      image: behroozam/redis:k8s
      env:
        - name: MASTER
          value: "true"
      ports:
        - containerPort: 6379
      resources:
        limits:
          cpu: "0.1"
    - name: sentinel
      image: behroozam/redis:k8s
      env:
        - name: SENTINEL
          value: "true"
      ports:
        - containerPort: 26379
  initContainers:
  - name: init-sysctl
    image: busybox
    command:
    - /bin/sh
    - -c
    - |
      sysctl -w net.core.somaxconn=10000
      sysctl -w net.ipv4.ip_local_port_range='1024 65535'
    securityContext:
      privileged: true
  nodeSelector:
    redis: "true"